### ISSUE TITLE
autonav_interface commented out in package set but still present in deployments

### ISSUE THREAD

**Issue by wieset** [esa-prl/deployments-orogen-rover_deployments#1]
When bootstrapping our rock installation, I get an autoproj error because autonav_interface is still present in the orogen and manifest in the rover_deployments but commented out in the package set. I would suggest to also comment it out here (or move it to a separate deployment / package set) to allow a successful bootstrap from scratch.

This relates to https://github.com/esa-prl/rover-package_set/issues/2

**Comment by levingerdes** [comment]
Good catch! I currently don't have a rock installation to test this unfortunately and assumed that it works because we didn't get feedback on this proposed resolution. Moving it to a separate package set feels like an overkill in my opinion and it's still a generic package, just a private one. So, although it's a bit ugly, I'd say go ahead and comment it out.

**Comment by wieset** [comment]
Ok, will do, thx!
